services:
  kafka:
    extends:
      file: docker-compose.yml
      service: kafka

  registry:
    extends:
      file: docker-compose.yml
      service: registry

  jaws-libp:
    extends:
      file: docker-compose.yml
      service: jaws-libp

  effective:
    extends:
      file: docker-compose.yml
      service: effective
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CUSTOM_CRT_URL=http://pki.jlab.org/JLabCA.crt