services:
  kafka:
    extends:
      file: compose.yaml
      service: kafka

  registry:
    extends:
      file: compose.yaml
      service: registry

  jaws:
    extends:
      file: compose.yaml
      service: jaws

  effective:
    extends:
      file: compose.yaml
      service: effective
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CUSTOM_CRT_URL=http://pki.jlab.org/JLabCA.crt