services:
  kafka:
    extends:
      file: deps.yaml
      service: kafka

  registry:
    extends:
      file: deps.yaml
      service: registry

  cli:
    extends:
      file: deps.yaml
      service: cli

  effective:
    hostname: effective
    container_name: effective
    healthcheck:
      test: test $(ps | grep jaws | wc -l) -gt 1
      start_period: 30s
      start_interval: 5s
#      interval: 30s      # waiting for https://github.com/docker/compose/issues/10830
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      jaws:
        condition: service_healthy
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"