services:
  kafka:
    extends:
      file: deps.yml
      service: kafka

  registry:
    extends:
      file: deps.yml
      service: registry

  jaws-libp:
    extends:
      file: deps.yml
      service: jaws-libp

  effective:
    hostname: effective
    container_name: effective
    depends_on:
      - jaws-libp
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"