services:
  zookeeper:
    extends:
      file: deps.yml
      service: zookeeper

  kafka:
    extends:
      file: deps.yml
      service: kafka

  registry:
    extends:
      file: deps.yml
      service: registry

  jaws:
    extends:
      file: deps.yml
      service: jaws

  effective:
    hostname: effective
    container_name: effective
    depends_on:
      - jaws
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"